# -*- coding: utf-8 -*-
"""
1.1
author: Zhong Peng(pengmany@outlook.com)
createDate: 2016-11-25
generate paper - author csv file from all metadata of APS.
This file is the pre-precess for generating the results,
the result of this file is in format3), but there're some problem in author name(\n)
the results have three files:
format 3), format 1) and 2) is generated by paper_all_author_all_format3.py, 
paper_all_author_all_format2.py and paper_all_author_all_format1.py respectively.
1) two columns: paper, author list of string type, and every row represents one paper(doi)
2) N columns: paper, authorA, authorB...., every author has stand in one column.
3) two columns: paper, author, and every row represents a pair of one paper and one author,
    e.t. each paper P has 3 authors(A, B, C), then there're 3 lines: (P, A), (P, B), (P, C)
"""
import os
import csv
import json


if os.name == "posix":
    base_path = r"/media/zhongpeng/Datas/APS-DATA/aps-dataset-metadata-2013"
elif os.name == "nt":
    base_path = r"E:/APS-DATA/aps-dataset-metadata-2013"
else:
    print "error in init base_path"
    exit(0)

print base_path
final_li = list()
paper_without_author_li = list()
for root, dirs, files in os.walk(base_path):
    for file in files:
        print file
        path = os.path.join(root, file)
        f = open(path, "rb")
        data = json.load(f)
        f.close()
        doi = data["id"].encode('utf-8')
        if not("authors" in data):
            # print "file %s doesn't have author info" % path
            final_li.append((doi, ""))
            paper_without_author_li.append((doi, ))
        else:
            authors = data["authors"]
            if len(authors) == 0:
                final_li.append((doi, ""))
                paper_without_author_li.append((doi, ))
            else:
                for au in authors:
                    if "name" in au:
                        author = au["name"].encode('utf-8')
                    else:
                        paper_without_author_li.append((doi, ))
                    final_li.append((doi, author))
print "final_li generate over"

with open(r"paper_without_author.csv", "wb") as csvfile:
    writer = csv.writer(csvfile, dialect="excel")
    writer.writerows(paper_without_author_li)
print "paper_without_author.csv writes over"

with open(r"paper_all_author_all.csv", "wb") as csvfile:
    writer = csv.writer(csvfile, dialect="excel")
    writer.writerows(final_li)
print "result paper_all_author_all.csv writes over"
