# -*- coding: utf-8 -*-
"""
author: Zhong Peng
createDate: 2017-014-18
lastModified: 2017-04-18
according to the files generated by year_author_paper.py and origin citation file,
calculate author's citation numbers in his(or her) 10th academic career year.
"""
import csv
import os
import sys
sys.path.append("..")
from conf import config
from aps import process


if os.name == "nt":
    base_path = config.base_path_nt
elif os.name == "posix":
    base_path = config.base_path_posix
else:
    print "error in get base_path, unknow os"
    exit(0)

cited_citing_li_dic = dict()
origin_citation_path = os.path.join(base_path, r"../aps-dataset-citations-2013/aps-dataset-citations-2013.csv")
with open(origin_citation_path, "rb") as csvfile:
    reader = csv.reader(csvfile, dialect="excel")
    reader.next()
    for row in reader:
        if row[1] in cited_citing_li_dic:
            cited_citing_li_dic[row[1]].append(row[0])
        else:
            cited_citing_li_dic[row[1]] = [row[0], ]
print "cited_citing_li_dic generates over"

for year in xrange(2002, 2013):
    final_li = list()
    with open(r"../result/AuthorCitationByYear/author_paper_%s.csv" % year, "rb") as csvfile:
        reader = csv.reader(csvfile, dialect="excel")
        for row in reader:
            count = 0
            paper_li = row[1][2: -2].split("', '")
            for cited_paper in paper_li:
                if cited_paper in cited_citing_li_dic:
                    for citing_paper in cited_citing_li_dic[cited_paper]:
                        if int(process.get_paper_year_by_doi(citing_paper)) <= year:
                            count += 1
            tmp_li.append(row[0])
            tmp_li.append(count)
            final_li.append(tmp_li)
    print "year %s process over" % year
    with open(r"../result/AuthorCitationByYear/author_citation_%s.csv" % year, "wb") as csvfile:
        writer = csv.writer(csvfile, dialect="excel")
        writer.writerows(final_li)
    print "year %s result writes over" % year
